# Name of this connection profile
profile.mame = ExampleProfile
# Time to sleep in seconds before attempting a reconnect. Set to 0 to disable automatic reconnecting.
profile.reconnectDelay = 5

# DAPNET hostname or IP address
dapnet.hostname = dapnet-core-server
# DAPNET port number
dapnet.port = 43434
# DAPNET authentication name
dapnet.auth.name = transmitterName
# DAPNET authentication key
dapnet.auth.key = transmitterKey

# Backend (raspager) host name or IP address
transmitter.hostname = raspager-server
# Backend port number
transmitter.port = 1337
# Timeout in seconds for keep alive requests. Set to 0 to disable.
transmitter.timeout = 30
